INSERT INTO departments (name, description)
VALUES ("Management", "Management oversees the other departments and evaluates the effectiveness of current containment protocols.  Revisions to containment and changes to protocols require review and acceptance from management before they can be implemented."),
       ("Security", "Security maintains the site perimeter, enforces proper containment of anomalous entities, and provides escorts during the relocation of hazardous entities and objects.  Security is to remain armed and armored at all times."),
       ("Legal", "The Legal Team handles political opinion, country relations, and public appearance.  They utilize news sources and media to mask information leaks, hide foundation secrets from the public eye, and rewrite documents and books to hide anomalies."),
       ("Light Containment Research and Analysis", "Light Containment Research and Analysis refers to the scientists and researchers assigned to certain anomalous entities and objects deemed slightly hazardous or safe in nature.  They are tasked with the study, quantifying, and cataloging of data acquired through testing and research."),
       ("Light Containment Testing", "Light Containment Testing refers to the human subjects utilized for the testing of anomalous entities and objects deemed slightly hazardous or safe in nature.  T-Class are unpaid and attained through diplomatic agreements with countries.  They are most commonly: death row or life-sentence with no parole inmates, prisoners or war, low-class traitors, or missing persons located by authorities at least 2 years after having been reported missing.  This position must be seen as ideal and provided as a reward to T-Class employees that do not dissent from authority."),
       ("Heavy Containment Research and Analysis", "Heavy Containment Research and Analysis refers to the scientists and researchers assigned to certain anomalous entities and objects deemed extremely hazardous.  They are tasked with the study, quantifying, and cataloging of data acquired through testing and research."),
       ("Heavy Containment Testing", "Heavy Containment Testing refers to the human subjects utilized for the testing of anomalous entities and objects deemed extremely hazardous.  They are most commonly: death row or life-sentence with no parole inmates, prisoners or war, low-class traitors, or missing persons located by authorities at least 2 years after having been reported missing.  This position must be seen as punishment for the disobedience of T-Class Employees and the expectation must be that they are not going to last in this department.");

INSERT INTO roles (title, salary, department_id)
VALUES ("Site Overseer", 250000.00, 1),
       ("Site Coordinator", 200000.00, 1),
       ("Lead Researcher (Sector 01)", 150000.00, 1),
       ("Lead Researcher (Sector 02)", 150000.00, 1),
       ("Lead Researcher (Sector 03)", 150000.00, 1),
       ("Lead Researcher (Sector 04)", 175000.00, 1),
       ("Captain of the Guard", 175000.00, 1),
       ("Perimeter Guard", 75000.00, 2),
       ("Containment Security", 100000.00, 2),
       ("Enforcement Officer", 125000.00, 2),
       ("Lawyer", 150000.00, 3),
       ("Civil Diplomat", 100000.00, 3),
       ("Public Specialist", 100000.00, 3),
       ("Historic Revisioner", 100000.00, 3),
       ("Light Containment Scientist", 100000.00, 4),
       ("Light Containment Researcher", 75000.00, 4),
       ("Light Containment T-Class", 0.00, 5),
       ("Heavy Containment Scientist", 150000.00, 6),
       ("Heavy Containment Researcher", 125000.00, 6),
       ("Heavy Containment T-Class", 0.00, 7);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES ("[REDACTED]", "[REDACTED]", "1", null),
       ("Markson", "Rowley", 2, 1),
       ("Silvia", "Anderson", 3, 2),
       ("Walter", "Bishop", 4, 2),
       ("Victor", "Terrance", 5, 2),
       ("Javius", "Cameron", 6, 2),
       ("Frederick", "Mourner", 7, 2),
       ("Harry", "McGee", 8, 7),
       ("Amir", "Yemen", 8, 7),
       ("Ava", "Kern", 8, 7),
       ("Rachel", "Mercer", 8, 7),
       ("Jeremiah", "Stone", 9, 7),
       ("Ursela", "Whitaker", 9, 7),
       ("Matt", "Knocks", 9, 7),
       ("Leroy", "Tools", 9, 7),
       ("Justin", "Jackson", 10, 7),
       ("Huell", "Ford", 10, 7),
       ("Susan", "Reynolds", 11, 2),
       ("Bartholomew", "Brown", 11, 2),
       ("Olga", "Gart", 12, 2),
       ("Cynthia", "Harlem", 13, 2),
       ("Eli", "White", 14, 2),
       ("Quinten", "Harrison", 15, 3),
       ("Krawley", "Mulder", 15, 4),
       ("Matthew", "Graven", 15, 5),
       ("Terry", "Ivastedder", 16, 3),
       ("Heinrick", "Zeinhar", 16, 3),
       ("Jeremy", "Jacks", 16, 4),
       ("Pearl", "Knight", 16, 4),
       ("Jonathan", "Merryweather", 16, 5),
       ("Kendrick", "Meyers", 16, 5),
       ("Daphne", "Danvers", 17, 3),
       ("Carmen", "Paige", 17, 3),
       ("Luke", "Chessmire", 17, 4),
       ("Cameron", "Smith", 17, 4),
       ("Ron", "Grey", 17, 5),
       ("Joey", "Hemmingway", 17, 5),
       ("Kiera", "Decker", 18, 6),
       ("Drake", "Fineheart", 19, 6),
       ("Carl", "Cage", 20, 6),
       ("Tristin", "Mitchell", 20, 6),
       ("Kyson", "Clarks", 20, 6),
       ("Gary", "Gibson", 20, 6);